### ISSUE TITLE
Color

### ISSUE THREAD

**Issue by Mark2Mark** [mekkablue/ShowVerticalMetrics#2]
I could change it myself and push a pull request, but I’m not sure if you’d like the idea of changing the color to a slightly stronger one. The line is okay, but the type is barely readable in this glowing green on white. And my eyes are usually still quite good 😆

**Comment by mekkablue** [comment]
I haven’t been happy with the colors either. :-/

**Comment by qassimhaider** [comment]
to Grey please !

**Comment by mekkablue** [comment]
I added a way to set your custom color. See the readme for details.

**Comment by qassimhaider** [comment]
perfect, thanks
